name:    "Escuela Argentina en Nueva York"
abbr:    "EANY"
url:     "http://escuelaargentinany.com"

source:      _source
destination: _deploy
markdown:    redcarpet

exclude: [README.md, sass, config.rb, .sass-cache]


## Additional or alternative options
# description: "Description for site or subheading."
# paginate: 10
# permalink: pretty
# permalink: /:categories/:title
# pygments: true

## Tips
# url: "http://example.com"  # NO trailing slash '/'